// <auto-generated />
namespace CarsRent.BL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class cars_and_contracts_model_changed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cars_and_contracts_model_changed));
        
        string IMigrationMetadata.Id
        {
            get { return "202109260757432_cars_and_contracts_model_changed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
